# Generated by Django 5.1 on 2024-09-20 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExpResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exp_id', models.IntegerField()),
                ('index', models.IntegerField()),
                ('self_val', models.TextField()),
                ('computer_val', models.TextField()),
                ('reaction_time', models.TextField()),
                ('time', models.TextField(null=True)),
                ('option', models.TextField()),
                ('other_option', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='RequestData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_type', models.IntegerField(unique=True)),
                ('message', models.TextField()),
            ],
        ),
    ]
