# Generated by Django 3.2.25 on 2024-11-04 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expresult',
            name='id',
        ),
        migrations.AlterField(
            model_name='expresult',
            name='exp_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='expresult',
            name='inputValue',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='expresult',
            name='qinmidu',
            field=models.IntegerField(),
        ),
    ]
