# Generated by Django 5.1 on 2024-09-11 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_populate_requestdata'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exp_id', models.IntegerField()),
                ('index', models.TextField()),
                ('self_val', models.TextField()),
                ('computer_val', models.TextField()),
                ('reaction_time', models.TextField()),
                ('time', models.TextField()),
            ],
        ),
    ]
