# Generated by Django 3.2.25 on 2024-11-04 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_expresult_qinmidu'),
    ]

    operations = [
        migrations.AddField(
            model_name='expresult',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='expresult',
            name='exp_id',
            field=models.IntegerField(),
        ),
    ]
