# Generated by Django 5.1 on 2024-09-11 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_expresult'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expresult',
            name='exp_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='expresult',
            name='index',
            field=models.IntegerField(unique=True),
        ),
    ]
