# Generated by Django 5.1 on 2024-09-11 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alter_expresult_exp_id_alter_expresult_index'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expresult',
            name='index',
            field=models.IntegerField(),
        ),
    ]
