# Generated by Django 5.1 on 2024-09-12 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_alter_expresult_index'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expresult',
            name='index',
            field=models.IntegerField(unique=True),
        ),
    ]
